=== AndreasLantz/PEGA/files/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
	<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="xs:https://andreaslantz.github.io/PEGA/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	  <xs:element name="receipt">
		<xs:complexType>
		  <xs:sequence>
			<xs:element name="header">
			  <xs:complexType>
				<xs:sequence>
				  <xs:element name="image">
					<xs:complexType>
					  <xs:sequence>
						<xs:element type="xs:string" name="src"/>
						<xs:element name="height">
						  <xs:complexType>
							<xs:simpleContent>
							  <xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="units"/>
							  </xs:extension>
							</xs:simpleContent>
						  </xs:complexType>
						</xs:element>
						<xs:element name="width">
						  <xs:complexType>
							<xs:simpleContent>
							  <xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="units"/>
							  </xs:extension>
							</xs:simpleContent>
						  </xs:complexType>
						</xs:element>
						<xs:element type="xs:string" name="title"/>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element type="xs:string" name="storeName"/>
				  <xs:element name="address">
					<xs:complexType>
					  <xs:sequence>
						<xs:element type="xs:string" name="street"/>
						<xs:element type="xs:string" name="city"/>
						<xs:element type="xs:string" name="postalCode"/>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element type="xs:string" name="organizationNumber"/>
				  <xs:element type="xs:string" name="registrationId"/>
				  <xs:element type="xs:string" name="email"/>
				  <xs:element type="xs:string" name="phone"/>
				  <xs:element type="xs:string" name="text" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
			  </xs:complexType>
			</xs:element>
			<xs:element name="transaction">
			  <xs:complexType>
				<xs:choice maxOccurs="unbounded" minOccurs="0">
				  <xs:element name="items">
					<xs:complexType>
					  <xs:sequence>
						<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
						  <xs:complexType>
							<xs:sequence>
							  <xs:element type="xs:string" name="transactionType"/>
							  <xs:element type="xs:string" name="itemId"/>
							  <xs:element type="xs:string" name="itemName"/>
							  <xs:element name="itemPrice">
								<xs:complexType>
								  <xs:simpleContent>
									<xs:extension base="xs:string">
									  <xs:attribute type="xs:string" name="currency" use="optional"/>
									</xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
							  </xs:element>
							  <xs:element type="xs:string" name="itemQuantity"/>
							  <xs:element name="totalItemPrice">
								<xs:complexType>
								  <xs:simpleContent>
									<xs:extension base="xs:string">
									  <xs:attribute type="xs:string" name="currency" use="optional"/>
									</xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
							  </xs:element>
							  <xs:element name="itemDiscount">
								<xs:complexType>
								  <xs:sequence>
									<xs:element type="xs:string" name="text"/>
									<xs:element type="xs:string" name="discountPercent"/>
									<xs:element name="fixedAmount">
									  <xs:complexType>
										<xs:simpleContent>
										  <xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="currency" use="optional"/>
										  </xs:extension>
										</xs:simpleContent>
									  </xs:complexType>
									</xs:element>
									<xs:element type="xs:string" name="discountQuantity"/>
									<xs:element type="xs:string" name="totalDiscount"/>
								  </xs:sequence>
								</xs:complexType>
							  </xs:element>
							  <xs:element name="vat">
								<xs:complexType>
								  <xs:sequence>
									<xs:element type="xs:string" name="vatPercent"/>
								  </xs:sequence>
								</xs:complexType>
							  </xs:element>
							  <xs:element name="itemAddon">
								<xs:complexType>
								  <xs:sequence>
									<xs:element type="xs:string" name="addonName"/>
									<xs:element type="xs:string" name="addonPrice"/>
								  </xs:sequence>
								</xs:complexType>
							  </xs:element>
							</xs:sequence>
						  </xs:complexType>
						</xs:element>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element type="xs:string" name="text" maxOccurs="unbounded" minOccurs="0"/>
				  <xs:element name="discounts">
					<xs:complexType mixed="true">
					  <xs:sequence>
						<xs:element type="xs:string" name="text" minOccurs="0"/>
						<xs:element type="xs:string" name="discountAmount" minOccurs="0"/>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element type="xs:string" name="totalItems"/>
				  <xs:element name="amountDue">
					<xs:complexType>
					  <xs:simpleContent>
						<xs:extension base="xs:string">
						  <xs:attribute type="xs:string" name="currency"/>
						</xs:extension>
					  </xs:simpleContent>
					</xs:complexType>
				  </xs:element>
				  <xs:element name="paymentDetails">
					<xs:complexType mixed="true">
					  <xs:sequence>
						<xs:element name="cash" minOccurs="0">
						  <xs:complexType>
							<xs:sequence>
							  <xs:element name="amountReceived">
								<xs:complexType>
								  <xs:simpleContent>
									<xs:extension base="xs:string">
									  <xs:attribute type="xs:string" name="currency"/>
									</xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
							  </xs:element>
							  <xs:element name="change">
								<xs:complexType>
								  <xs:simpleContent>
									<xs:extension base="xs:string">
									  <xs:attribute type="xs:string" name="currency"/>
									</xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
							  </xs:element>
							</xs:sequence>
						  </xs:complexType>
						</xs:element>
						<xs:element name="card" minOccurs="0">
						  <xs:complexType>
							<xs:sequence>
							  <xs:element name="amountReceived">
								<xs:complexType>
								  <xs:simpleContent>
									<xs:extension base="xs:string">
									  <xs:attribute type="xs:string" name="currency"/>
									</xs:extension>
								  </xs:simpleContent>
								</xs:complexType>
							  </xs:element>
							  <xs:element type="xs:string" name="cardType"/>
							  <xs:element type="xs:string" name="authMethod"/>
							  <xs:element type="xs:string" name="storeId"/>
							  <xs:element type="xs:string" name="terminal"/>
							  <xs:element type="xs:string" name="aid"/>
							  <xs:element type="xs:string" name="transactionDate"/>
							  <xs:element type="xs:string" name="cardNumber"/>
							  <xs:element type="xs:string" name="transactionType"/>
							  <xs:element type="xs:string" name="sweRef"/>
							  <xs:element type="xs:string" name="ref"/>
							  <xs:element type="xs:string" name="tvr"/>
							  <xs:element type="xs:string" name="tsi"/>
							  <xs:element type="xs:string" name="runNumber"/>
							  <xs:element type="xs:string" name="contactless"/>
							</xs:sequence>
						  </xs:complexType>
						</xs:element>
						<xs:element type="xs:string" name="text" maxOccurs="unbounded" minOccurs="0"/>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element name="totalTax">
					<xs:complexType>
					  <xs:sequence>
						<xs:element name="taxLevel" maxOccurs="unbounded" minOccurs="0">
						  <xs:complexType>
							<xs:sequence>
							  <xs:element type="xs:string" name="vatPercentage"/>
							  <xs:element type="xs:string" name="vatTotal"/>
							  <xs:element type="xs:string" name="net"/>
							  <xs:element type="xs:string" name="gross"/>
							</xs:sequence>
						  </xs:complexType>
						</xs:element>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				</xs:choice>
			  </xs:complexType>
			</xs:element>
			<xs:element name="footer">
			  <xs:complexType mixed="true">
				<xs:sequence>
				  <xs:element type="xs:string" name="text" maxOccurs="unbounded" minOccurs="0"/>
				  <xs:element name="cashier">
					<xs:complexType>
					  <xs:sequence>
						<xs:element type="xs:string" name="cashierId"/>
						<xs:element type="xs:string" name="cashierName"/>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element name="line">
					<xs:complexType>
					  <xs:sequence>
						<xs:element type="xs:string" name="text"/>
						<xs:element type="xs:string" name="lineId"/>
					  </xs:sequence>
					</xs:complexType>
				  </xs:element>
				  <xs:element type="xs:string" name="receiptDate"/>
				  <xs:element type="xs:string" name="receiptNumber"/>
				  <xs:element type="xs:string" name="controlUnit"/>
				</xs:sequence>
			  </xs:complexType>
			</xs:element>
		  </xs:sequence>
		</xs:complexType>
	  </xs:element>
	</xs:schema>

=== AndreasLantz/PEGA/files/receipt4.xml
<?xml version="1.0" encoding="UTF-8"?>
<receipt
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="schema.xsd">
	<header>
		<image>
			<src>yoursourcehere.xxx</src>
			<height units="xxx"></height>
			<width units="xxx"></width>
			<title>yourlogonamehere</title>
		</image>
		<storeName>MATBODEN EKTORP C</storeName>
		<address>
			<street>EKTORPSVÄGEN 4</street>
			<city>NACKA</city>
			<postalCode>13147</postalCode>
		</address>
		<organizationNumber>556712-8508</organizationNumber>
		<phone>08-716 13 80</phone>
		<text>kr</text>
	</header>
	<transaction>
		<items>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>1</itemId>
					<itemName>RUSH ANANAS</itemName>
					<itemPrice currency="SEK">13,95</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">13,95</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
					<itemAddon>
						<addonName>+ PANT</addonName>
						<addonPrice>1,00</addonPrice>
					</itemAddon>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>2</itemId>
					<itemName>DIGESTIVE EKO</itemName>
					<itemPrice currency="SEK">25,95</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="">25,95</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>3</itemId>
					<itemName>RAMLÖSA CITRUS</itemName>
					<itemPrice currency="SEK">12,95</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">12,95</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
					<itemAddon>
						<addonName>+ PANT</addonName>
						<addonPrice>1,00</addonPrice>
					</itemAddon>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>4</itemId>
					<itemName>RED DEVIL</itemName>
					<itemPrice currency="SEK">14,95</itemPrice>
					<itemQuantity>4</itemQuantity>
					<totalItemPrice currency="">59,80</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
		</items>
		<discounts>
			<text>Ölkorv 3 för 39:-</text>
			<discountAmount>5,85</discountAmount>
		</discounts>
		<text>ATT BETALA SEK (7 ARTIKLAR)</text>
		<totalItems>7</totalItems>
		<amountDue currency="SEK">108,80</amountDue>
		<paymentDetails>
			<card>
				<amountReceived currency="SEK">108,80</amountReceived>
				<cardType>Debit MasterCard</cardType>
				<authMethod>Personlig kod</authMethod>
				<storeId>715219</storeId>
				<terminal>3 / 61203190</terminal>
				<aid>A0000000041010</aid>
				<transactionDate>2018-08-12T18:42:22</transactionDate>
				<cardNumber>************3777</cardNumber>
				<transactionType>KORTKÖP</transactionType>
				<sweRef>Ca1 7 000 SWE 831334</sweRef>
				<ref>612031901527</ref>
				<tvr>0000001000</tvr>
				<tsi>E800</tsi>
			</card>
			<text>BELOPP GODKÄNT AV KUND</text>
			<text>SPARA KVITTOT, KUNDENS EXEMPLAR</text>
			<text>TILLBAKA SEK</text>
			<text>0.00</text>
		</paymentDetails>
		<totalTax>
			<taxLevel>
				<vatPercentage>12</vatPercentage>
				<vatTotal>11,66</vatTotal>
				<net>97,14</net>
				<gross>108,80</gross>
			</taxLevel>
		</totalTax>
	</transaction>
	<footer>
		<text>Öppettider:</text>
		<text>Mån-Lör 8-21</text>
		<text>Sön 8-20</text>
		<text>Tack och välkommen åter!</text>
		<cashier>
			<cashierId>121</cashierId>
			<cashierName>Andreas</cashierName>
		</cashier>
		<receiptDate>2018-08-12T18:42:19</receiptDate>
		<receiptNumber>003-16169 [601559]</receiptNumber>
		<controlUnit>RIHTT100710002986</controlUnit>
	</footer>
</receipt>

=== AndreasLantz/PEGA/files/receipt3.xml
<?xml version="1.0" encoding="UTF-8"?>
<receipt
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="schema.xsd">
	<header>
		<image>
			<src>yoursourcehere.xxx</src>
			<height units="xxx"></height>
			<width units="xxx"></width>
			<title>yourlogonamehere</title>
		</image>
		<storeName>The English Bookshop</storeName>
		<address>
			<street>Svartbacksgatan 19</street>
			<city>Uppsala</city>
		</address>
		<organizationNumber>5565162418</organizationNumber>
		<registrationId>0000000000000001</registrationId>
		<email>info@bookshop.se</email>
		<phone>018-10 05 10</phone>
		<text>Visit us at www.bookshop.se</text>
	</header>
	<transaction>
		<items>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>1</itemId>
					<itemName>Books/Böcker</itemName>
					<itemPrice currency="SEK">430,00</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">430,00</totalItemPrice>
					<vat>
						<vatPercent>6</vatPercent>
					</vat>
				</item>
		</items>
		<text>1.00xITEMs</text>
		<totalItems>1</totalItems>
		<amountDue currency="SEK"></amountDue>
		<paymentDetails>
			<card>
				<amountReceived currency="SEK">430,00</amountReceived>
				<ref>B5FD3000000009913</ref>
				<runNumber>000000160882</runNumber>
			</card>
		</paymentDetails>
		<totalTax>
			<taxLevel>
				<vatPercentage>6</vatPercentage>
				<vatTotal>24,34</vatTotal>
			</taxLevel>
		</totalTax>
	</transaction>
	<footer>
		<text>Öppet köp 14 dagar mot kvitto</text>
		<text>(gäller ej specialbeställningar)</text>
		<text>The Uppsala English Bookshop</text>
		<text>** THANK YOU FOR YOUR CUS...</text>
		<text>*** ORIGINAL</text>
		<line>
			<lineId>00</lineId>
		</line>
		<receiptDate>2018-09-17T17:09:00</receiptDate>
		<receiptNumber>181867</receiptNumber>
	</footer>
</receipt>

=== AndreasLantz/PEGA/files/receipt1.xml
<?xml version="1.0" encoding="UTF-8"?>
<receipt
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="schema.xsd">
	<header>
		<image>
			<src>yoursourcehere.xxx</src>
			<height units="xxx"></height>
			<width units="xxx"></width>
			<title>yourlogonamehere</title>
		</image>
		<storeName>Willys Hemma</storeName>
		<address>
			<city>Saltsjöbaden</city>
		</address>
		<organizationNumber>556163-2232</organizationNumber>
		<phone>08-7480830</phone>
	</header>
	<transaction>
		<items>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>1</itemId>
					<itemName>FLÄSKFILE 540G</itemName>
					<itemPrice currency="SEK">22,90</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">22,90</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>2</itemId>
					<itemName>FELIX HALLONSYLT 250G</itemName>
					<itemPrice currency="SEK">19,90</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">19,90</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>3</itemId>
					<itemName>TIP TOP</itemName>
					<itemPrice currency="SEK">25,00</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">25,00</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>4</itemId>
					<itemName>SMABI MATLÅDA</itemName>
					<itemPrice currency="SEK">15,90</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">15,90</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>5</itemId>
					<itemName>PLASTKASSE VIT</itemName>
					<itemPrice currency="SEK">2,00</itemPrice>
					<itemQuantity>2</itemQuantity>
					<totalItemPrice currency="SEK">4,00</totalItemPrice>
					<vat>
						<vatPercent>25</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>6</itemId>
					<itemName>KVISTTOMATER</itemName>
					<itemPrice currency="SEK">42,90</itemPrice>
					<itemQuantity>0,570</itemQuantity>
					<totalItemPrice currency="SEK">24,45</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>7</itemId>
					<itemName>AVOKADO</itemName>
					<itemPrice currency="SEK">13,90</itemPrice>
					<itemQuantity>2</itemQuantity>
					<totalItemPrice currency="SEK">27,80</totalItemPrice>
					<itemDiscount>
						<text>2 * Rabatt:AVOKADO</text>
						<discountPercent></discountPercent>
						<fixedAmount currency="">3</fixedAmount>
						<discountQuantity>2</discountQuantity>
						<totalDiscount>6</totalDiscount>
					</itemDiscount>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>8</itemId>
					<itemName>POTATIS FAST</itemName>
					<itemPrice currency="SEK">11,90</itemPrice>
					<itemQuantity>1,475</itemQuantity>
					<totalItemPrice currency="SEK">17,55</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>9</itemId>
					<itemName>GRÄDDFIL 3DL EKO</itemName>
					<itemPrice currency="SEK">25,60</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">25,60</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>10</itemId>
					<itemName>GREVÉ 12 MÅN 28%</itemName>
					<itemPrice currency="SEK">124,00</itemPrice>
					<itemQuantity>0,647</itemQuantity>
					<totalItemPrice currency="SEK">80,23</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>11</itemId>
					<itemName>KALLES KAVIAR 300G</itemName>
					<itemPrice currency="SEK">26,50</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">26,50</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>12</itemId>
					<itemName>KOTLETT CA450G</itemName>
					<itemPrice currency="SEK">105,00</itemPrice>
					<itemQuantity>0,494</itemQuantity>
					<totalItemPrice currency="SEK">51,87</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>13</itemId>
					<itemName>EXTRA STRONG MINT</itemName>
					<itemPrice currency="SEK">14,90</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">14,90</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
		</items>
		<text>Totalt 17 varor</text>
		<totalItems>17</totalItems>
		<text>Totalt</text>
		<amountDue currency="SEK">356,87</amountDue>
		<paymentDetails>
			<card>
				<amountReceived currency="SEK">356,87</amountReceived>
				<cardType>Debit MasterCard</cardType>
				<authMethod>Personlig kod</authMethod>
				<storeId>2293561</storeId>
				<terminal>4 / 00083259</terminal>
				<aid>A0000000041010</aid>
				<transactionDate>2018-10-04T12:05:10</transactionDate>
				<cardNumber>************3777</cardNumber>
				<transactionType>KÖP</transactionType>
				<sweRef>KA1 6 000 SWE 115520</sweRef>
				<ref>000032595047</ref>
				<tvr>0000048000</tvr>
				<tsi>E8000</tsi>
				<contactless>KONTAKTLÖS</contactless>
			</card>
		</paymentDetails>
		<totalTax>
			<taxLevel>
				<vatPercentage>12</vatPercentage>
				<vatTotal>37,81</vatTotal>
				<net>315,06</net>
				<gross>352,87</gross>
			</taxLevel>
			<taxLevel>
				<vatPercentage>25</vatPercentage>
				<vatTotal>0,80</vatTotal>
				<net>3,20</net>
				<gross>4,00</gross>
			</taxLevel>
		</totalTax>
	</transaction>
	<footer>
		<text>SPARA KVITTOT</text>
		<text>Välkommen åter!</text>
		<text>Mån-Lör 8-21 Sön 9-21</text>
		<text>Tel: 08-7480830</text>
		<text>Du betjänades av</text>
		<cashier>
			<cashierId>41</cashierId>
			<cashierName>Sofia</cashierName>
		</cashier>
		<line>
			<text>Kassa</text>
			<lineId>4/169</lineId>
		</line>
		<receiptDate>2018-10-04T12:05:10</receiptDate>
	</footer>
</receipt>

=== AndreasLantz/PEGA/files/structure.xml
<?xml version="1.0" encoding="UTF-8"?>

<receipt
xmlns="https://andreaslantz.github.io/PEGA/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://andreaslantz.github.io/PEGA/ https://andreaslantz.github.io/PEGA/schema.xsd">
	<header>
		<image>
			<src></src>
			<height units=""></height>
			<width units=""></width>
			<title></title>
		</image>
		<storeName></storeName>
		<address>
			<street></street>
			<city></city>
			<postalCode></postalCode>
		</address>
		<organizationNumber></organizationNumber>
		<registrationId></registrationId>
		<email></email>
		<phone></phone>
		<text></text>
		<text></text>
		<text></text>
	</header>
	<transaction>
		<items>
				<item>
					<transactionType></transactionType>
					<itemId></itemId>
					<itemName></itemName>
					<itemPrice currency=""></itemPrice>
					<itemQuantity></itemQuantity>
					<totalItemPrice currency=""></totalItemPrice>
					<itemDiscount>
						<text></text>
						<discountPercent></discountPercent>
						<fixedAmount currency=""></fixedAmount>
						<discountQuantity></discountQuantity>
						<totalDiscount></totalDiscount>
					</itemDiscount>
					<vat>
						<vatPercent></vatPercent>
					</vat>
					<itemAddon>
						<addonName></addonName>
						<addonPrice></addonPrice>
					</itemAddon>
				</item>
				<item>
					<transactionType></transactionType>
					<itemId></itemId>
					<itemName></itemName>
					<itemPrice currency=""></itemPrice>
					<itemQuantity></itemQuantity>
					<totalItemPrice currency=""></totalItemPrice>
					<itemDiscount>
						<text></text>
						<discountPercent></discountPercent>
						<fixedAmount currency=""></fixedAmount>
						<discountQuantity></discountQuantity>
						<totalDiscount></totalDiscount>
					</itemDiscount>
					<vat>
						<vatPercent></vatPercent>
					</vat>
					<itemAddon>
						<addonName></addonName>
						<addonPrice></addonPrice>
					</itemAddon>
				</item>
		</items>
		<text></text>
		<text></text>
		<discounts>
			<text></text>
			<discountAmount></discountAmount>
		</discounts>
		<text></text>
		<text></text>
		<totalItems></totalItems>
		<amountDue currency=""></amountDue>
		<paymentDetails>
			<cash>
				<amountReceived currency=""></amountReceived>
				<change currency=""></change>
			</cash>
			<card>
				<amountReceived currency=""></amountReceived>
				<cardType></cardType>
				<authMethod></authMethod>
				<storeId></storeId>
				<terminal></terminal>
				<aid></aid>
				<transactionDate></transactionDate>
				<cardNumber></cardNumber>
				<transactionType></transactionType>
				<sweRef></sweRef>
				<ref></ref>
				<tvr></tvr>
				<tsi></tsi>
				<runNumber></runNumber>
				<contactless></contactless>
			</card>
			<text></text>
			<text></text>
		</paymentDetails>
		<text></text>
		<text></text>
		<totalTax>
			<taxLevel>
				<vatPercentage></vatPercentage>
				<vatTotal></vatTotal>
				<net></net>
				<gross></gross>
			</taxLevel>
			<taxLevel>
				<vatPercentage></vatPercentage>
				<vatTotal></vatTotal>
				<net></net>
				<gross></gross>
			</taxLevel>
			<taxLevel>
				<vatPercentage></vatPercentage>
				<vatTotal></vatTotal>
				<net></net>
				<gross></gross>
			</taxLevel>
		</totalTax>
	</transaction>
	<footer>
		<text></text>
		<text></text>
		<text></text>
		<text></text>
		<text></text>
		<cashier>
			<cashierId></cashierId>
			<cashierName></cashierName>
		</cashier>
		<line>
			<text></text>
			<lineId></lineId>
		</line>
		<receiptDate></receiptDate>
		<receiptNumber></receiptNumber>
		<controlUnit></controlUnit>
	</footer>
</receipt>

=== AndreasLantz/PEGA/files/receipt2.xml
<?xml version="1.0" encoding="UTF-8"?>
<receipt
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="schema.xsd">
	<header>
		<image>
			<src>yoursourcehere.xxx</src>
			<height units="xxx"></height>
			<width units="xxx"></width>
			<title>yourlogonamehere</title>
		</image>
		<storeName>Jarlaberg Nacka</storeName>
		<organizationNumber>969743-1519</organizationNumber>
		<phone>08-7184666</phone>
		<text>ÖPPET FÖR DIG!</text>
		<text>ALLA DAGAR</text>
		<text>9-20</text>
	</header>
	<transaction>
		<items>
				<item>
					<transactionType>Sale</transactionType>
					<itemId>1</itemId>
					<itemName>MJÖLK EKOLOGISK 3%</itemName>
					<itemPrice currency="SEK">14,95</itemPrice>
					<itemQuantity>1</itemQuantity>
					<totalItemPrice currency="SEK">14,95</totalItemPrice>
					<vat>
						<vatPercent>12</vatPercent>
					</vat>
				</item>
		</items>
		<text>Totalt 1 vara</text>
		<totalItems>1</totalItems>
		<text>Totalt</text>
		<amountDue currency="SEK">14,95</amountDue>
		<paymentDetails>
			<card>
				<amountReceived currency="SEK">14,95</amountReceived>
				<cardType>Debit Mastercard</cardType>
				<authMethod>Personlig Kod</authMethod>
				<storeId>532697</storeId>
				<terminal>1 / 00004098</terminal>
				<aid>A0000000041010</aid>
				<transactionDate>2018-08-11T15:12:27</transactionDate>
				<cardNumber>************3777</cardNumber>
				<transactionType>KÖP</transactionType>
				<sweRef>Ca1 6 000 SWE 314184</sweRef>
				<ref>000040983429</ref>
				<tvr>0000001000</tvr>
				<tsi>6800</tsi>
			</card>
		</paymentDetails>
		<totalTax>
			<taxLevel>
				<vatPercentage>12</vatPercentage>
				<vatTotal>1,60</vatTotal>
				<net>13,35</net>
				<gross>14,95</gross>
			</taxLevel>
		</totalTax>
	</transaction>
	<footer>
		<text>SPARA KVITTOT</text>
		<text>Välkommen åter</text>
		<text>TEL 08-718 46 66</text>
		<text>FAX 08-718 46 66</text>
		<text>Du betjänades av</text>
		<cashier>
			<cashierName>Dashti</cashierName>
		</cashier>
		<line>
			<text>Kassa</text>
			<lineId>1/186</lineId>
		</line>
		<receiptDate>2018-08-11T15:14:00</receiptDate>
	</footer>
</receipt>
